### ISSUE TITLE
Responsive menu not working

### ISSUE THREAD

**Issue by camstuart** [mdbootstrap/mdb-react-ui-kit#1]
When the browser is made smaller and the nav bar responds, the hamburger menu does not work (tested in chrome)

**Comment by JStrebeyko** [comment]
@camstuart did pull resolve the issue?

**Comment by RayKoren** [comment]
I am having this same issue. I downloaded and created the free version with create-react-app last week.
![image](https://user-images.githubusercontent.com/16106956/39485433-f5cc66c4-4d35-11e8-9353-aa65c55cae7c.png)

**Comment by Rotarepmi** [comment]
This issue should be closed. Please use `<NavbarToggler>` instead of simple `<button>`
