### ISSUE TITLE
Modal isn't working

### ISSUE THREAD

**Issue by bmmathe** [mdbootstrap/mdb-react-ui-kit#10]
Warning: Unknown props `onExited`, `appear`, `enter`, `exit` on div tag. Remove these props from the element. For details, see https://fb.me/react-unknown-prop
    in div (created by Fade)
    in Fade
    in div (created by TransitionGroup)
    in TransitionGroup

**Comment by badjem79** [comment]
same problem here

**Comment by smolenski-mikolaj** [comment]
Please change fade to false in line 62 in Modal.js file.
We'll fix it in the next release.
