### ISSUE TITLE
License for commecial use

### ISSUE THREAD

**Issue by srbala** [mdbootstrap/mdb-react-ui-kit#100]
Do user need buy license use React-Bootstrap-with-Material-Design? License.pdf indicate, I should. But website indicates free, please clear it for me.

> The most popular UI KIT for building responsive, mobile-first websites and apps - free for personal & commercial use.

**Comment by marveluck** [comment]
@srbala MDB Free is covered by MIT license. That basically means that it's free and unrestricted for personal and commercial use and you can create whatever you wish with it. 

You can use React-Bootstrap-with-Material-Design (free version - available here on GitHub) without any restrictions.
