### ISSUE TITLE
Attempted import error: 'MDBTableEditable' is not exported from 'mdbreact'.

### ISSUE THREAD

**Issue by OmarOmeiri** [mdbootstrap/mdb-react-ui-kit#101]
I'm trying to run this code from the documentation.
https://mdbootstrap.com/docs/react/tables/editable/

but I'm getting an import error from MDBTableEditable.

P.S:
I installed the package using `npm install mdbreact`

**Comment by OmarOmeiri** [comment]
I see it now, it is a PRO component.

**Comment by Fashad-Ahmed** [comment]
Can you please explain how you figure it out?

**Comment by dotku** [comment]
> Can you please explain how you figure it out?

It says on the doc page
