### ISSUE TITLE
Navigation within MDBDataTable using Arrow Keys.

### ISSUE THREAD

**Issue by zubairshakoorarbisoft** [mdbootstrap/mdb-react-ui-kit#110]
Hi,
I have an application, in which i am using editable cells to save data. So i need to go through cells using Arrow Keys(Up, Down, Left, Right).
Is there any feature provided in MDBDataTable Like this?

**Comment by pglejzer** [comment]
There no possible to do that at the moment.  I added the task to consider this in the future. Have a nice day.
