### ISSUE TITLE
Cursor on MDBInput component jumps when used with redux-form

### ISSUE THREAD

**Issue by cgero-eth** [mdbootstrap/mdb-react-ui-kit#111]
The cursor on the Input component always jumps at the end of the input when using it with redux-form (see [sanbox](https://codesandbox.io/s/still-smoke-psey7)).  
This is a known issue of redux-form but it looks like it can be fixed by changing the MDBInput component to extend React.PureComponent instead of React.Component (see [redux-form issue 3253](https://github.com/redux-form/redux-form/issues/3253) and [sanbox](https://codesandbox.io/s/KGXD07rz)).   

Could you consider changing the MDBInput component to extend React.PureComponent instead of React.Component?

**Comment by jakubchmura** [comment]
We are currently preparing to refactor this component. I will add your suggestion to the task list.

**Comment by krzysiu-w** [comment]
We'll try to add it in the next release :)
