### ISSUE TITLE
MDBDataTable searchingLabel issue

### ISSUE THREAD

**Issue by jferrandi** [mdbootstrap/mdb-react-ui-kit#112]
Using mdbreact v4.27.0 , the MDBDataTable prop searchingLabel is not working, the custom / i18n value is not applied. Neither no entry for it's placeholder is available.

https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/issues/68 issue about this problem, but still present

**Comment by zpvisla** [comment]
I have the same problem. The prop searchingLabel is not working.

**Comment by mateus-schultz** [comment]
I had this problem, but fixed by just changing `searchingLabel` to `searchLabel`.
They need to update the types file because it's outdated.

**Comment by krzysiu-w** [comment]
We'll update it in the next release (12.07) :)
