### ISSUE TITLE
MDBModal documentation out-of-date

### ISSUE THREAD

**Issue by davidjamesb** [mdbootstrap/mdb-react-ui-kit#113]
The documentation at https://mdbootstrap.com/docs/react/modals/basic/#docsTabsAPI does not describe some of the required props defined here:

https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/commit/25ae803b9121efe64a02c5d9e4466cf6ea908a3f#diff-56c036bdda02ab2369a9066ebbbd3e88

**Comment by krzysiu-w** [comment]
Hi!

Thanks for reporting that. I updated the documentation a few minutes ago :)
