### ISSUE TITLE
Mistake in the Quick start guide for the free version

### ISSUE THREAD

**Issue by Davut97** [mdbootstrap/mdb-react-ui-kit#115]
under : "Using SCSS files in Create-React-App project"
in step: "Step 3:  Create new folder asstes and put copied files into this and move this folder into src folder."
step 3 saying that we should create folder named "asstes" but when importing the library the documentation used "assets" : "import "./assets/scss/mdb-free.scss" .
https://mdbootstrap.com/docs/react/getting-started/quick-start/

**Comment by krzysiu-w** [comment]
Hi!

Thanks for reporting that. I fixed that a few minutes ago :)
