### ISSUE TITLE
Mistake in Modal generator for fluid modals

### ISSUE THREAD

**Issue by pajasry** [mdbootstrap/mdb-react-ui-kit#116]
## Bug
The modal generator doesn't generate fluids modals properly. Inconsistency with API.

## How to reproduce
Use [this](https://mdbootstrap.com/docs/react/modals/generator/l) and select some fluid option. The generated code don't work as fluid.

## Fix
Replace full-height with fullHeight, described [here](https://mdbootstrap.com/docs/react/modals/basic/#docsTabsAPI)

Please fix it for new users and save some times others for searching for errors in their code.

**Comment by krzysiu-w** [comment]
Hi!

Thanks for reporting that. I fixed that a few minutes ago :)
