### ISSUE TITLE
MDBSelect onChange

### ISSUE THREAD

**Issue by jpotter-kalm** [mdbootstrap/mdb-react-ui-kit#119]
We're still waiting on an onChange implementation for the MDBSelect. I was told it would be coming with the next update, and that was before the 4.27 update, and I don't see it in the 5.0 Alpha either. When can we reasonably expect the select to have onChange added? I need to know if I have to abandon the idea of using your select input and move on to an exteral library.

**Comment by krzysiu-w** [comment]
Hi!

We will add it in the next release (12.07) :) 

Keep coding!
