### ISSUE TITLE
modal typescript type error

### ISSUE THREAD

**Issue by shipcake** [mdbootstrap/mdb-react-ui-kit#120]
![image](https://user-images.githubusercontent.com/30076862/87654245-c8649e00-c780-11ea-980b-562cb3e65124.png)

**Comment by lefrankleal** [comment]
same issue here

please help!!

**Comment by LuisSic** [comment]
I had the same issue, they will fix in the next release. https://mdbootstrap.com/support/react/mdbmodal-reactjs/

**Comment by lefrankleal** [comment]
> I had the same issue, they will fix in the next release. https://mdbootstrap.com/support/react/mdbmodal-reactjs/

solved this by placing some default required props to the element

``
      inline={false}
      overflowScroll
      noClickableBodyWithoutBackdrop={true}
``

**Comment by LuisSic** [comment]
Thank you bro :D

**Comment by krzysiu-w** [comment]
Hi!

We'll add a fix for it in the next release (12.07) :)
