### ISSUE TITLE
MDBBtn & MDBNavLink showing errors...

### ISSUE THREAD

**Issue by tejasag** [mdbootstrap/mdb-react-ui-kit#126]
So the other day I was making a webpage and used MDBBtn & MDBNavLink property in it and both of them gave me this error. This error occurred even if any one of these was in the code...

File with MDBNavlink - https://sourceb.in/cb67faaf18
File with MDBBtn - https://srcb.in/2da6c4d6d2

_I am open to contact on discord -_  `CyberKnight#0001`

I am using the latest version of mdbreact as well as react
![image](https://user-images.githubusercontent.com/67542663/90760636-cfdb1200-e2ff-11ea-92a9-cec823e5120a.png)

**Comment by kelvin-addweb** [comment]
@tejasag @mattonit @apati04 @awoyele @catchmareck I am facing the same issue if anyone able to find any solution related to this issue then let me know.

**Comment by kelvin-addweb** [comment]
@tejasag can you please reopen this issue?

**Comment by johnthomsonn** [comment]
I am having the exact same issue, any information would be greatly appreciated!

**Comment by johnthomsonn** [comment]
This answer fixed it for me: https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/issues/149
