### ISSUE TITLE
React MDB NavLink changing the page url but not the view

### ISSUE THREAD

**Issue by nh916** [mdbootstrap/mdb-react-ui-kit#127]
I have implemented MDB landing page with navigation and when clicking on the navigation link the url of the page does change but the page remains exactly the same and the view does not change at all. i have checked for hours and I could not find what the error was and I gave up, so I am wondering if there is any errors that we can fix in the MDB code. Please let me know. I would love to continue using MDB!

here is all the code that I am using for this small project

https://github.com/nh916/safuja-butterfly

**Comment by krzysiu-w** [comment]
Hi!

You have to remove <Router> tags from your FullPageIntroWithFixedTransparentNavbar components and everything will work :)
