### ISSUE TITLE
Popover / Tooltip CPU usage

### ISSUE THREAD

**Issue by Vrq** [mdbootstrap/mdb-react-ui-kit#128]
The Popover / Tooltip component is using Timeouts/Intervals which leads to unnecessary CPU usage in the background.

The problematic code is:
https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/blob/master/src/components/Popper/Popper.js#L32

Is there a possibility to redo the component to not cause CPU usage?

**Comment by Vrq** [comment]
@pglejzer are you aware of this issue?
On Safari the web app is heating crazy because of this code. :(

**Comment by MariaAbadi** [comment]
@marveluck @smolenski-mikolaj @pglejzer can anyone please have a look at this? 
It looks like you are the maintainers of this project :)

**Comment by pglejzer** [comment]
Yes, we are. I added this problem to our task to do to fix it. We will try to add a new version in 2/3 weeks.
