### ISSUE TITLE
Dependency of React 16 is not updated

### ISSUE THREAD

**Issue by dasarishiv** [mdbootstrap/mdb-react-ui-kit#13]
its mentioned that version 4.1.0 is updated for React 16. but its package.json have dependency : "react": "^15.6.1",
    "react-dom": "^15.6.1",

which cause multiple node_module installation dependency error:

invariant.js:42 Uncaught Error: Element ref was specified as a string (ripple) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).
    at invariant (invariant.js:42)
    at coerceRef (react-dom.development.js:6736)
    at reconcileSingleElement (react-dom.development.js:7532)
    at reconcileChildFibers (react-dom.development.js:7635)
    at reconcileChildrenAtExpirationTime (react-dom.development.js:7756)
    at reconcileChildren (react-dom.development.js:7747)
    at finishClassComponent (react-dom.development.js:7881)
    at updateClassComponent (react-dom.development.js:7850)
    at beginWork (react-dom.development.js:8225)
    at performUnitOfWork (react-dom.development.js:10224)

**Comment by hunterdt** [comment]
I've got the same issue.

**Comment by joselevelsup** [comment]
I have been getting the same issue when using the navbar example from the docs.

**Comment by woodie12** [comment]
I am getting the same issue here for the nav bar, so I uninstall React 16.0 version and install 15.6.1 version react and  react-dom instead

**Comment by smolenski-mikolaj** [comment]
Hello,
We've updated our product to the latest React version. Please delete mdbreact from package.json and then add to dependencies this line:

"mdbreact":"git+https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design.git#react-upgrade"

We'll update it also in npm with the next release of mdbreact.

Regards

**Comment by jstgermain** [comment]
that "fix" did not work for me

**Comment by smolenski-mikolaj** [comment]
What are Your errors? If console still shows same errors, it means that You haven't reinstall mdbreact properly.

**Comment by jstgermain** [comment]
I deleted the mdbreact file from node_modules and changed the package.json, did npm install and get same error. I then blew away entire node_modules, and reinstalled, same error. Docker could be messing up, so I will try to reinstall entire app today and do a build. I will keep you posted. Thanks for the quick response.

**Comment by pmbanugo** [comment]
mdbreact or mdbootstrap? what I installed is the mdbootstrap package and it's the folder I see in node_modules

**Comment by jstgermain** [comment]
So the react update branch is the one installed, but no styles are loading. No more errors.

**Comment by smolenski-mikolaj** [comment]
We've made a new 'step by step' instruction of MDB React installation. If Your problems are still not resolved please follow this guide: https://mdbootstrap.com/react/react-bootstrap-getting-started/.
