### ISSUE TITLE
Bundle size increased 2x since 4.26.0

### ISSUE THREAD

**Issue by Vrq** [mdbootstrap/mdb-react-ui-kit#136]
It looks like the bundle size has grown dramatically (from 59kB to 132kB gzipped!) 

This is probably because including MomentJS (a very bloated and now deprecated date library)

My suggestion would be to switch to a different library to reduce the bundle size.

Resource: https://bundlephobia.com/result?p=mdbreact@4.27.0 it l

**Comment by Vrq** [comment]
The bundle size went to over 280kb (already minified + gzipped) which is crazy compared 4.25 where it was 60kb - do you have plans to address it? @krzysiu-w @AAndrasiuk @pglejzer 🙈 

https://bundlephobia.com/result?p=mdbreact@5.0.0

**Comment by pglejzer** [comment]
Yes, we have plans to remove unnecessary dependency from our package. Thanks for the report.

**Comment by Vrq** [comment]
@pglejzer  it looks like the 'moment' dependency is still there: https://bundlephobia.com/package/mdbreact@5.1.0 - could you please double-check it?

**Comment by pglejzer** [comment]
@Vrq, you have to ask @krzysiu-w or another developer to check it. I don't work here anymore.
