### ISSUE TITLE
Error with Navbar component due to React 16

### ISSUE THREAD

**Issue by Blennouill** [mdbootstrap/mdb-react-ui-kit#14]
**Context**
I develop an SPA app with React 16.2.0.
I'm using the last version of mdbreact : 4.1.0
I would like to use the Navbar component.

**Steps to reproduce**
1. Create a test project
`npx react-create-app test-issue`

2. Check if the react version is >= 16.0.0

3. In App.js, replace the content with the followings
```import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { Navbar } from 'mdbreact'

class App extends Component {
  render() {
    return (
      <div className="App">
        <Navbar color="indigo" dark expand="md" fixed="top" scrolling>
          </Navbar>
      </div>
    );
  }
}

export default App;`
import React, { Component } from 'react';
import logo from './logo.svg';
import './App.css';
import { Navbar } from 'mdbreact'

class App extends Component {
  render() {
    return (
      <div className="App">
        <Navbar color="indigo" dark expand="md" fixed="top" scrolling>
          </Navbar>
      </div>
    );
  }
}

export default App;
```

4. Launch the app
`npm start `

5. An error is display
> Element ref was specified as a string (navbar) but no owner was set. You may have multiple copies of React loaded. (details: https://fb.me/react-refs-must-have-owner).

**Problem**

After some deeply research, I found the source of the trouble.
https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/blob/65b8f6b66559ed6bbaed5eff3c485d355e724e2a/src/components/Navbar.js#L75

String is not anymore accepted for ref.
You can have a look on the official documentation of React :
[https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refs](https://reactjs.org/docs/refs-and-the-dom.html#legacy-api-string-refsl)

According to the above informations and the changelog (cf https://github.com/facebook/react/blob/master/CHANGELOG.md), it is very much possible that the functionnalty was deleted.

**Comment by sboudouk** [comment]
Encoutering the same issue. Anyway you found to fix it ?

EDIT: A fix is, as said by the dev team, to remove `mdbreact` from project and add it as:

`“mdbreact”:”git+https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design.git#react-upgrade”`

in dependencies, then, run `npm install`.

It fixed the error for me even if the navbar does not have any style now.

**Comment by kinsomicrote** [comment]
@sboudouk solution does not work for me.
I have a new error;
```
./node_modules/mdbreact/node_modules/react-dom/lib/BeforeInputEventPlugin.js
Module build failed: Error: ENOENT: no such file or directory, open '/home/jioke/lab/projects/feca/node_modules/mdbreact/node_modules/react-dom/lib/BeforeInputEventPlugin.js'
```

**Comment by R3DST0RM** [comment]
@sboudouk 
> It fixed the error for me even if the navbar does not have any style now.

I can confirm that behaviour also affecting me. The navbar has no more styles.

**Comment by JStrebeyko** [comment]
Hi guys. Several things have been updated in the project lately, including the way the navbar is referenced or the git repository path is added to **package.json**. Check out these latest developments and let us know whether any of your issues here got solved.

**Comment by rayitopy** [comment]
Facing this issue too

**Comment by JStrebeyko** [comment]
https://mdbootstrap.com/support/navbar-4/ does your version of MDB have a `ref` attribute in navbar? Cheers

**Comment by rayitopy** [comment]
@JStrebeyko Yes it has

**Comment by mbefokam** [comment]
I am facing the same issue too

**Comment by DrewParsons** [comment]
Has this been fixed yet?  I have the same styling issue.  No errors, but the navbar doesn't have styling.

**Comment by smolenski-mikolaj** [comment]
The problem should be fixed with the next release (next week).

**Comment by Rotarepmi** [comment]
I assume that issue can be closed.
