### ISSUE TITLE
How to choose an specific pro version? (Pro version - React)

### ISSUE THREAD

**Issue by maxrojasdev** [mdbootstrap/mdb-react-ui-kit#140]
Hello there,

The new 5.0.0 version is breaking down my app.
How can downgrade to the version 4.27.0 and **still having the pro functions**?
I found something like this in mdbootstrap Forum:
`"dependencies": { "mdbreact": "git+https://oauth2:YOUR_TOKEN@git.mdbootstrap.com/mdb/react/re-pro.git#dev"}`

Thanks

**Comment by pglejzer** [comment]
if you are a pro user with access to GitLab you can specify depends with mdbreact with a specific version.  Like that "git+https://oauth2:YOUR_TOKEN@git.mdbootstrap.com/mdb/react/re-pro.git#4.27.0".
