### ISSUE TITLE
Setting toggle to false doesn't work

### ISSUE THREAD

**Issue by emsoaldin** [mdbootstrap/mdb-react-ui-kit#143]
I've needed my toggled data to stay open even if I click inside of it.  I've read in the docs of DropdownItem Properties that there is an option toggle={false}, that should prevent closing dropdown on click.

Now the issue is: This doesn't work. It still closes if I click anywhere inside of a Dropdown
Here is how I use it in the code: MDBDropdownItem toggle={false}

Expected behavior: Dropdown shouldn't close when something inside is clicked

React version: 17.0.1
MDB version: 5.0.1

**Comment by jindrichkuba** [comment]
Hi, 

for me is working e.stopPropagation();

The event.stopPropagation() method stops the bubbling of an event to parent elements, preventing any parent event handlers from being executed.

**Comment by krzysiu-w** [comment]
Hi!

Thanks for reporting that. We'll fix it in the next release, in 2/3 weeks :)
