### ISSUE TITLE
Sorting state is unconsistent

### ISSUE THREAD

**Issue by ontanj** [mdbootstrap/mdb-react-ui-kit#148]
I've experienced some issues with sorting that could be separated into two different bugs.

### Sorting direction

When the table header is pressed in order to to sort, the direction always toggles between ascending and descending, even when I press a new column. I'd expect it to toggle when I press the selected column again, but not when I go to a new column. In the latter case I'd expect it to first sort either according to the provided `sort` attribute of the columns objects, or always in either ascending or descending direction.

### Wrong values from `onSort`

The direction coming from the `onSort` callback when a new column is pressed is always "asc", independently of the display of data. (Which toggles, as described above.) It seems, however, that when clicking a column with attribute `sort: "desc"`, `onSort` takes three click to pass "desc", so somehow the correct direction "desc" is stored internally but not passed from `onSort` the first time.

## Steps to reproduce

Create a fresh React application
```bash
npx create-react-app my-app --template typescript
cd my-app
npm install mdbreact
```
and replace the content of App.tsx with the following.
```typescript
import React from "react";
import { MDBDataTable } from "mdbreact";
import "./App.css";
import "@fortawesome/fontawesome-free/css/all.min.css";
import "bootstrap-css-only/css/bootstrap.min.css";
import "mdbreact/dist/css/mdb.css";

function App() {
  const data = [
    { letter: "a", number: 1 },
    { letter: "b", number: 2 },
    { letter: "c", number: 3 },
    { letter: "d", number: 4 },
    { letter: "e", number: 5 },
    { letter: "f", number: 6 },
  ];
  return (
    <div className="App">
      <MDBDataTable
        data={{
          columns: [
            { label: "letters", field: "letter", sort: "asc" },
            { label: "numbers", field: "number", sort: "desc" },
          ],
          rows: data,
        }}
        onSort={(s) => console.log(s)}
      />
    </div>
  );
}

export default App;
```

**Comment by krzysiu-w** [comment]
Hi!

Thanks for reporting this issue. We will fix it in the next release (12.07) :)

Keep coding!
