### ISSUE TITLE
It's not importing any components

### ISSUE THREAD

**Issue by shabaz-ejaz** [mdbootstrap/mdb-react-ui-kit#16]
I am using React and React DOM versions 15.4.2.

When I try to import components like this: 
```
import React, { Component, PropTypes } from 'react';
import { Button, Modal, ModalBody, ModalHeader, ModalFooter } from 'mdbreact';
```

PHPStorm gives me errors saying `cannot resolve symbol 'Modal' `

When I click on the button to show the modal I get the following error in the console:

![2018-02-07_10h22_51](https://user-images.githubusercontent.com/29374282/35911144-e373c57a-0bf0-11e8-9e14-959602280da6.png)

I am using `  "mdbreact": "^4.1.0",`

**Comment by blaw023** [comment]
I am also having the same issue. 

I put "mdbreact":"git+https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design.git#react-upgrade" in the dependencies as advised but still not working.

**Comment by shabaz-ejaz** [comment]
Yep, same here. I also tried that but wouldn't work. I'm sticking to Semantic UI React as I feel this library is not stable enough for a production site yet.

**Comment by blaw023** [comment]
I agree. I would love to use it but there's too many issues at the moment.

**Comment by JStrebeyko** [comment]
Hi guys, thanks for the feedback. The above mentioned solution seems to be effective only for React 16 and higher, so please update your dependencies if it's possible. As of now there's no task assigned for curating this backward-compatibility issue.

**Comment by Rotarepmi** [comment]
I assume that this issue can be closed.
