### ISSUE TITLE
Dropdown menu position issue

### ISSUE THREAD

**Issue by flowfree** [mdbootstrap/mdb-react-ui-kit#164]
I created a new React app and install MDB as described in this page: 

https://mdbootstrap.com/docs/b5/react/getting-started/installation

and then copy the Dropdown code snippet from the docs to my `App.js` file:

```
// src/App.js

import React from 'react';
import { MDBDropdown, MDBDropdownMenu, MDBDropdownToggle, MDBDropdownItem, MDBDropdownLink } from 'mdb-react-ui-kit';

export default function App() {
  return (
    <section className="p-4 text-center">
      <MDBDropdown>
        <MDBDropdownToggle>Dropdown</MDBDropdownToggle>
        <MDBDropdownMenu>
          <MDBDropdownItem>
            <MDBDropdownLink tag='button' type='button'>
              Action
            </MDBDropdownLink>
          </MDBDropdownItem>
          <MDBDropdownItem>
            <MDBDropdownLink tag='button' type='button'>
              Another action
            </MDBDropdownLink>
          </MDBDropdownItem>
          <MDBDropdownItem>
            <MDBDropdownLink tag='button' type='button'>
              Something else here
            </MDBDropdownLink>
          </MDBDropdownItem>
        </MDBDropdownMenu>
      </MDBDropdown>
    </section>
  );
}
```

But when the button gets clicked, the popup menu is displayed at the top left of the page:

<img width="300" alt="mdb-dropdown" src="https://user-images.githubusercontent.com/9797761/146636347-94ab2318-22a7-4c45-a53d-acd98fad5568.png">

Also adding `dropup`, `dropleft`, and `dropright` to the `MDBDropdown` component doesn't work as well. I am not sure if this is a bug or I missed something.

**Edit: MDB version 2.1.0**

**Comment by krzysiu-w** [comment]
Hi!

That was an issue caused by the ripple reference passed to the button component (which dropdown uses). After today's release, everything should work :)

Keep coding!
