### ISSUE TITLE
TimePicker can not get the value I set

### ISSUE THREAD

**Issue by recallwei** [mdbootstrap/mdb-react-ui-kit#165]
I have updated to the 2.2.0 version.
Timepicker - add setTime property to change a value programatically
I do not see the setTime property when use TimePicker.
How can I get the time I picked?

**Comment by krzysiu-w** [comment]
Hi!

It seems there's a typo in our documentation. You can use the customValue instead of setTime. If you don't want to set the value and just want to get it - you can use the getValue property. It should look like that (using buttons):

```
import React, { useState } from 'react';
import { MDBBtn, MDBTimepicker } from 'mdb-react-ui-kit';

export default function App() {
  const [customValue, setCustomValue] = useState('06:30 PM');
  return (
    <>
      <MDBTimepicker getValue(e => console.log(e)) customValue={customValue} />
      <div className='mt-4'>
        <MDBBtn onClick={() => setCustomValue('10:15 AM')}>10:15 AM</MDBBtn>
        <MDBBtn onClick={() => setCustomValue('09:45 PM')}>09:45 PM</MDBBtn>
      </div>
    </>
  );
}
```

Sorry for that.

Keep coding!
