### ISSUE TITLE
ReferenceError: document is not defined

### ISSUE THREAD

**Issue by GorlikItsMe** [mdbootstrap/mdb-react-ui-kit#166]
I use next.js + Typescript

When i create `modaltest.tsx` and place the same code like in [example](https://mdbootstrap.com/docs/b5/react/components/modal/#section-basic-example) i geting error
```
ReferenceError: document is not defined

Call stack

fe
file:/D:/GithubProjects/nextjs-shop/node_modules/mdb-react-ui-kit/dist/mdb-react-ui-kit.js (1:36248)
```

**Comment by Wojstan** [comment]
You could try adding this before your component return:

if (typeof window === "undefined") {
  return (<></>);
}
