### ISSUE TITLE
Question: mdbreact vs mdb-react-ui-kit - which package is better?

### ISSUE THREAD

**Issue by jainam-shah-cygnet** [mdbootstrap/mdb-react-ui-kit#169]
I have searched for react package of mdb and found 2 different packages, so which package should I use to creating react app ?
1. https://www.npmjs.com/package/mdbreact
2. https://www.npmjs.com/package/mdb-react-ui-kit

**Comment by krzysiu-w** [comment]
Hi!

The newest and most supporting package is the `mdb-react-ui-kit` (MDB5 React). It is created with React 17, Bootstrap 5, TypeScript. The older one (`mdbreact` - MDB4 React) is created mainly with React 16 and Bootstrap 4.

I recommend using mdb-react-ui-kit while creating your react app. It has fresh styles and the package weighs less. But it doesn't have all of the plugins from the previous version. We are still producing them, so if there's something you have to use that is only in the MDB4 React - use this one instead :) The MDB5 package also gets updated more frequently.

You can read more or check components in our documentation pages:

MDB5 React: https://mdbootstrap.com/docs/b5/react/
MDB4 React: https://mdbootstrap.com/docs/react/

Keep coding!

**Comment by jainam-shah-cygnet** [comment]
Hi @krzysiu-w ,

Thanks for exploring the difference.

Here one more thing I have noticed is MDB4 has dependency of material-ui packages (`@material-ui/core`, `material-ui-pickers`), but MDB5 has not any dependency of material-ui or it's packages.

So MDB5 has only dependent on bootstrap?

Thanks

**Comment by krzysiu-w** [comment]
The MDB5 is almost dependent only on Bootstrap 5. There are some plugins like chart.js (if not only) we still use, but we gave up using most of the external solutions (like i.e. MUI). In MDB5 React we developed our components from scratch using our logic, so the package weighs less and is fresher a lot :)

**Comment by jainam-shah-cygnet** [comment]
Hi @krzysiu-w,

Thanks for the clarifications of dependencies. This is very helpful for me.
