### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by mornya** [mdbootstrap/mdb-react-ui-kit#171]
The following error occurred at Next.js runtime.
MDB Version: `4.0.0`, `4.1.0`

<img width="401" alt="image" src="https://user-images.githubusercontent.com/1917573/178257227-c21945f9-82ca-4614-ba34-080e58583afa.png">

**Comment by krzysiu-w** [comment]
Hi!

This error was fixed in today's release so everything should work now :)
