### ISSUE TITLE
MDBModal keeps display:block after 2nd time closed

### ISSUE THREAD

**Issue by Frank683** [mdbootstrap/mdb-react-ui-kit#173]
I have a modal dialog defined as below:

```
        <MDBModal show={detailsModalVisible} onHide={() => _setVisibleDetailsModal(false)}>
          <MDBModalDialog size="lg" centered="true">
            <MDBModalContent>
              <div className="container">
                <MDBModalBody className="px-0">
                  {detailsModalContent}
                </MDBModalBody>
              </div>
            </MDBModalContent>
          </MDBModalDialog>
        </MDBModal>
```

When it is shown for the first time the DOM looks like this:

![image](https://user-images.githubusercontent.com/14088575/211028893-d895c70a-35de-47eb-8562-e70d9f9b86af.png)

When I close the dialog DOM looks like this:

![image](https://user-images.githubusercontent.com/14088575/211028952-19f00592-6822-4cef-b349-d146acb8af66.png)

When I open the dialog a 2nd time and close it again, the dialog disappears, the modal opacity is set to 0% but the element is still blocking the UI, being rendered above everything else. It seems the element stlye "display:block" is not removed from the div.

![image](https://user-images.githubusercontent.com/14088575/211029731-ee5c54a7-a238-4527-9407-b6c5c27bbfee.png)

The only "workaround" is suppressing the rendering of the MDBModal at all when detailsModalVisible is false but that also takes away the fade animation.

Is this a bug or am I missing something?
Any advise would be appreciated.

Thanks and best regards,
Frank

**Comment by gbujanski** [comment]
I checked the example from our documentation and it works fine. I need to know what the `_setVisibleDetailsModal` method does. This is probably causing the issue. Notice that in our examples we change the visibility of the modal to `onShow`.

**Comment by Frank683** [comment]
@gbujanski I think now I know what causes the issue.
It's not related to how often I open/close the dialog but to how I close it.
If I click the "x" button on the top right everything is fine but if I close the dialog by clicking outside of it or by hitting ESC neither the onHide() nor the onHidePrevented() eventhandlers get called and thus the state is not changed.

Since my component is class based I can't use the useState hook and have to rely on onHide and onHidePrevented to fire. That's the difference to your demo implementation.

![image](https://user-images.githubusercontent.com/14088575/217028269-81ad2318-6fe9-480c-ba92-1bffef3a376d.png)


![image](https://user-images.githubusercontent.com/14088575/217027389-7b7cd4f8-8559-4dc0-adec-bf4bb3f0040c.png)

![image](https://user-images.githubusercontent.com/14088575/217028685-0f20217f-91ea-4905-b0d8-e2fd2d1e2761.png)

**Comment by Frank683** [comment]
Hi @gbujanski or any other maintainer?

Can I expect a fix for this issue?
Given my previous explanation it should be possible to reproduce it.
What do you think?

Best,
Frank

**Comment by gbujanski** [comment]
Thanks! This will make it easier for us to fix this. onHide should also fire after the modal is closed by an outside click or esc button. 
We will fix it as soon as possible

**Comment by Frank683** [comment]
Hi, is there any timeline planned for the fix?

Best,
Frank

**Comment by gbujanski** [comment]
Fix was added in the last version. Have you updated MDB React to version 6.1.0?

**Comment by Frank683** [comment]
> Fix was added in the last version. Have you updated MDB React to version 6.1.0?

Now I have and it's working fine now.
Thought I would see a notification here that this issue was fixed with release xyz.
Thanks!
