### ISSUE TITLE
Module parse failed error

### ISSUE THREAD

**Issue by Lan-megumi** [mdbootstrap/mdb-react-ui-kit#174]
I am using the `Carousel` component, but the following error is displayed while running, 

I refer to the [Basic example](https://mdbootstrap.com/docs/react/components/carousel/#section-basic-example) in the official website, and this my code:

```jsx
const testingData = [
    { id: 0, source: 'https://mdbootstrap.com/img/new/slides/041.jpg' },
    { id: 1, source: 'https://mdbootstrap.com/img/new/slides/041.jpg' },
    { id: 2, source: 'https://mdbootstrap.com/img/new/slides/041.jpg' }
  ]
  return (
    <div>
      <MDBCarousel showControls showIndicators>
        {testingData.map((item) => (
          <MDBBreadcrumbItem key={item.id} itemId={item.id} src={item.source} alt='...' />
        ))}
      </MDBCarousel>
    </div>
  )
```
However, an error occurred during Cli compilation:
```
[11:48:16] Error - [webpack] 'dist':
./node_modules/.pnpm/mdb-react-ui-kit@6.0.0_tsihu7gne6rofuhotxstmzec2e/node_modules/mdb-react-ui-kit/dist/mdb-react-ui-kit.esm.js 724:36
Module parse failed: Unexpected token (724:36)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|         role: "progressbar",
|         ...p,
>         "aria-valuenow": Number(f) ?? a,
|         "aria-valuemin": Number(u),
|         "aria-valuemax": Number(c),
 @ ./lib/webparts/videoCarouselWebpart/components/VideoCarouselWebpart.js 5:0-66 21:28-39 21:149-166
 @ ./lib/webparts/videoCarouselWebpart/VideoCarouselWebpartWebPart.js
```
It looks like a loader is missing ? 

This is my `package.json`
```json
 "dependencies": {
    "@fortawesome/fontawesome-free": "^6.4.0",
    "@microsoft/sp-core-library": "1.17.0",
    "@microsoft/sp-lodash-subset": "1.17.0",
    "@microsoft/sp-office-ui-fabric-core": "1.17.0",
    "@microsoft/sp-property-pane": "1.17.0",
    "@microsoft/sp-webpart-base": "1.17.0",
    "mdb-react-ui-kit": "^6.0.0",
    "react": "17.0.1",
    "react-dom": "17.0.1",
    "tslib": "2.3.1"
  },
```
> This project is built by [SharePoint](https://learn.microsoft.com/en-us/sharepoint/dev/)

Is there a dependency package I didn't install?

**Comment by gbujanski** [comment]
It seems that something is missing in the webpack configuration. Are you using a custom webpack configuration? Please send this configuration. We'll check what's going on.

**Comment by Lan-megumi** [comment]
> It seems that something is missing in the webpack configuration. Are you using a custom webpack configuration? Please send this configuration. We'll check what's going on.

Thank you for your reply. Unfortunately, it's been a while and I have forgotten the specific details of the projects I worked on at that time. If you need the webpack configuration, you can take a look at the current configuration of the project generated by SharePoint by default.
