### ISSUE TITLE
MDBCollapse does not have onHide and onShow events

### ISSUE THREAD

**Issue by JasperHorn** [mdbootstrap/mdb-react-ui-kit#176]
This documentation: https://mdbootstrap.com/docs/react/components/collapse/#docsTabsAPI shows there are onHide and onShow events.

Neither event is actually there is practice...

**Comment by gbujanski** [comment]
I checked it. and everything seems to be working:

```       
<MDBCollapse show={showShow} onHide={console.log('hide')}>
    Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim
    keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
</MDBCollapse>
```

**Comment by JasperHorn** [comment]
Uh.... no? That test is no good.

You should do

    <MDBCollapse show={showShow} onHide={() => console.log('hide')}>
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. Nihil anim
        keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident.
    </MDBCollapse>

The sample you provided may seem to work because it calls the function (and assigns the return value to the onHide attribute) each time the code is rendered. If you're not convinced of that, try this doing `onJumpUpAndDown={console.log('hi')}` and you should see that the effects that you saw earlier weren't because of the event firing properly.

**Comment by gbujanski** [comment]
You're right. I did the test correctly, but I pasted the code with the error here :facepalm:. This event has been working since the last version. I didn't notice that you add an issue before the 6.1.0 release. Updating the MDB to the latest version should solve your problem
