### ISSUE TITLE
uncaught TypeError: Failed to execute 'getComputedStyle' occurs and keeps racking up but doesnt crash anything

### ISSUE THREAD

**Issue by mingisdingis** [mdbootstrap/mdb-react-ui-kit#177]
I'm receiving this error in the console that shows up specifically when I interact with the sign-in form on my app. It doesn't crash the app, but it seems to accrue more instances of the same error on a regular interval every few seconds. 
it's happening on the machines of several of my teammates, so it doesn't seem to be an isolated incident. Hoping someone could shed some light on whether or not this is even something we can fix or if it's a problem with the library itself.

![Screenshot 2023-06-01 at 10 19 20 AM](https://github.com/mdbootstrap/mdb-react-ui-kit/assets/98193716/d258e6ad-58cb-4f8e-968b-ba81874417c9)

**Comment by N3koSempai** [comment]
me too. the source appears to be this:                      
![error](https://github.com/mdbootstrap/mdb-react-ui-kit/assets/43711237/2df58b99-d4e2-4aa2-855e-7aaf465fbd86)

**Comment by gbujanski** [comment]
Can you post the code that causes this error? We'll check why this is happening

**Comment by mingisdingis** [comment]
i happens most reliably on this page as soon as i click into one of the input fields. thanks for taking a look, i appreciate it



import React, { useState } from "react";
import { useLoginMutation } from "../redux/apiSlice";
import { useNavigate } from "react-router-dom";
import {
  MDBInput,
  MDBCol,
  MDBRow,
  MDBBtn,
  MDBContainer
} from 'mdb-react-ui-kit';

function Signin() {
  const [login] = useLoginMutation();
  const [username, setUsername] = useState("");
  const [password, setPassword] = useState("");
  const navigate = useNavigate();

  const handleSubmit = async (e) => {
    e.preventDefault();
    const response = await login({ username, password });
    if (response.error) {
      if ( response.error.status === 422) {
        alert(response.error.data.detail[0].msg);
      } else {
        alert(response.error.data.detail);
      }
    } else {
      navigate("/");
    }
  };

  return (
    <>
      <MDBContainer className="signin mb-10">
        <MDBRow>
          <MDBCol />
          <MDBCol>
            <form onSubmit={(e) => handleSubmit(e)}>
              <MDBInput
                className="form-input mb-4"
                type="email"
                label="Email address"
                onChange={(e) => setUsername(e.target.value)}
              />
              <MDBInput
                className="form-input mb-4"
                type="password"
                label="Password"
                onChange={(e) => setPassword(e.target.value)}
              />
              <MDBBtn outline rounded type="submit" color="info" block>
                Sign in
              </MDBBtn>
            </form>
          </MDBCol>
          <MDBCol />
        </MDBRow>
      </MDBContainer>
    </>
  );
}

export default Signin;

**Comment by gbujanski** [comment]
The code seems incomplete. The submit button is missing and the form tag is not closed. I added the missing code and unfortunately, I don't have this error. What version of MDB React are you using?

**Comment by simple40** [comment]
> me too. the source appears to be this: ![error](https://user-images.githubusercontent.com/43711237/244860418-2df58b99-d4e2-4aa2-855e-7aaf465fbd86.jpeg)

Hey was the resolved ?

**Comment by simple40** [comment]
> i happens most reliably on this page as soon as i click into one of the input fields. thanks for taking a look, i appreciate it
> 
> import React, { useState } from "react"; import { useLoginMutation } from "../redux/apiSlice"; import { useNavigate } from "react-router-dom"; import { MDBInput, MDBCol, MDBRow, MDBBtn, MDBContainer } from 'mdb-react-ui-kit';
> 
> function Signin() { const [login] = useLoginMutation(); const [username, setUsername] = useState(""); const [password, setPassword] = useState(""); const navigate = useNavigate();
> 
> const handleSubmit = async (e) => { e.preventDefault(); const response = await login({ username, password }); if (response.error) { if ( response.error.status === 422) { alert(response.error.data.detail[0].msg); } else { alert(response.error.data.detail); } } else { navigate("/"); } };
> 
> return ( <> <form onSubmit={(e) => handleSubmit(e)}> <MDBInput className="form-input mb-4" type="email" label="Email address" onChange={(e) => setUsername(e.target.value)} /> <MDBInput className="form-input mb-4" type="password" label="Password" onChange={(e) => setPassword(e.target.value)} /> Sign in </> ); }
> 
> export default Signin;

were you able to resolve the error

**Comment by mako3577** [comment]
The issue was fixed in version 6.2.0.
