### ISSUE TITLE
Duplicated onClick event handler on Button

### ISSUE THREAD

**Issue by shilu911** [mdbootstrap/mdb-react-ui-kit#18]
If I pass an onClick attribute to the Button component as a prop, then there will be 2 onClick attributes on the button element(line 80 and line 83 of Button.js)

**Comment by JStrebeyko** [comment]
Yes, it's true. What feedback are you getting from the compilation terminal / console?

**Comment by shilu911** [comment]
On Chrome, it works fine, but on Safari it needs double click to trigger the onClick event handler I pass to the the Button component, because the first click trigger the wave animation but not trigger the onClick event handler, I must click the button again quickly before the animation is finished then I am able to trigger the onClick event handler.

**Comment by JStrebeyko** [comment]
Has been noted. Contributions are welcome!

**Comment by JStrebeyko** [comment]
Hi, just dropping by to let people now, that <a href="https://github.com/mui-org/material-ui/issues/4532">issue is widely known</a> and it has <a href="https://github.com/zilverline/react-tap-event-plugin">known workarounds</a>. We encourage commits solving this problem, even though browsers are moving away from the said iOS 300ms delay causing it.
