### ISSUE TITLE
Navigation Bar does not show

### ISSUE THREAD

**Issue by kinsomicrote** [mdbootstrap/mdb-react-ui-kit#19]
### Expected behavior
I expected the navigation bar with links to show

### Actual behavior
Only the form shows

### Your working environment and MDB version information
React 16, and the github version of MDB

### Resources (screenshots, code snippets etc.)
```
import React, { Component } from 'react';
import { Navbar, NavbarBrand, NavbarNav, NavbarToggler, Collapse, NavItem, NavLink, Dropdown, DropdownToggle, DropdownMenu, DropdownItem } from 'mdbreact';
import { BrowserRouter as Router } from 'react-router-dom';

class NavigationBar extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      collapse: false,
      isWideEnough: false,
      dropdownOpen: false
    };
  this.onClick = this.onClick.bind(this);
  this.toggle = this.toggle.bind(this);
  }
  
  onClick(){
    this.setState({
        collapse: !this.state.collapse,
    });
  }
  
  toggle() {
    this.setState({
        dropdownOpen: !this.state.dropdownOpen
    });
  }
    
    render() {
      return (
        <Router>
          <Navbar color="indigo" dark expand="md" scrolling>
            <NavbarBrand href="/">
              <strong>Navbar</strong>
            </NavbarBrand>
            { !this.state.isWideEnough && <NavbarToggler onClick = { this.onClick } />}
            <Collapse isOpen = { this.state.collapse } navbar>
              <NavbarNav className="ml-auto">
                <NavItem>
                    <NavLink className="nav-link" to="#">Home</NavLink>
                </NavItem>
                <NavItem>
                    <NavLink className="nav-link" to="#">Features</NavLink>
                </NavItem>
                <NavItem>
                  <NavLink className="nav-link" to="#">Pricing</NavLink>
                </NavItem>
                  <form className="form-inline">
                    <input className="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search"/>
                  </form>
              </NavbarNav>
            </Collapse>
          </Navbar>
        </Router>
      );
    }
}

export default NavigationBar
```

**Comment by JStrebeyko** [comment]
Hi there. I wasn't able to recreate the issue - are you getting any compilation/console errors? The Navbar at the top of the App is built the same way as the above component - are its contents not being displayed, too? Best, Kuba

**Comment by kinsomicrote** [comment]
@JStrebeyko No, I am not getting any compilation/console errors.
Here is the link to the code repo, can you please help me take a look?

**Comment by kinsomicrote** [comment]
I copied and pasted the code for Navigation found [here](https://mdbootstrap.com/react/components/navbar/), and I still experienced the same issue.
@JStrebeyko could this be a bug?

**Comment by JStrebeyko** [comment]
hi @kinsomicrote, I did not get the link to the repo you mention in your first comment. Copying the code from the <a href="https://mdbootstrap.com/react/components/navbar/">MDB React Docs</a>, compiling and serving it works on my end. Have you tried inspecting it with <a href="https://chrome.google.com/webstore/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi?hl=en">React DevTools</a>?

**Comment by mattonit** [comment]
closed due to no response
