### ISSUE TITLE
how to get production build which will put images, bundlejs , index.html with linked to minified css and minified js as well with images or resources

### ISSUE THREAD

**Issue by kkbeheramca** [mdbootstrap/mdb-react-ui-kit#21]
hi i am new to react and found mdbootstrap is good for new development, 
i download the source code and did "install npm" followed by "npm start" which builds and starts well in browser. 
but when run the command "npm run build" it minified js "mdbreact.js" corresponding map file along with that some font files and one svg file and place it in "dist" directory. but i can not find any index.html with linking to minified.js and minified.css.

can anybody help me getting the config for a production env. so that it will create all necessary steps to put everything required for production version.

thank you

**Comment by mattonit** [comment]
What exactly are you trying to do? Do you use MDB React as base for your project or you want to modify our library and use it in your CRA-based app?

**Comment by mattonit** [comment]
closed due to no response
