### ISSUE TITLE
Mdb React Fontawesome loaded twice

### ISSUE THREAD

**Issue by shaggyrec** [mdbootstrap/mdb-react-ui-kit#23]
### I think the second time an item was imported one of elements mdb/
![image](https://user-images.githubusercontent.com/20976187/37656370-ea9d5e64-2c58-11e8-89c7-d75e295cf363.png)

**Comment by JStrebeyko** [comment]
Bug report submitted. PR welcome

**Comment by Rotarepmi** [comment]
I assume that this issue can be closed
