### ISSUE TITLE
Failing install ...

### ISSUE THREAD

**Issue by jamesladd** [mdbootstrap/mdb-react-ui-kit#29]
Cloned the repo and tried to install and run but this fails.
Not sure why peer dependencies have to be installed myself - can't these be in package.json?

Not a good experience for a first timer with React MDB, which is sad as the project looks so good.

### Expected behavior
clone the repository
cd to the directory with the repository
npm install (don't use yarn)
run the app using npm start
enjoy!

### Actual behavior
clone the repository
cd to the directory with the repository
npm install - failed as there are peer dependencies.

### Your working environment and MDB version information
npm --version = 5.6.0
node --version = v9.10.1

### Resources (screenshots, code snippets etc.)

npm WARN ajv-keywords@3.1.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.0.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN react-motion-ui-pack@0.10.3 requires a peer of react@0.14.x || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-motion-ui-pack@0.10.3 requires a peer of react-dom@0.14.x || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.2 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

**Comment by jamesladd** [comment]
When I installed 'yarn' and ran 'yarn install' as suggested in doc it failed.
However, in another page I saw the command 'yarn' on its own and I tried that.
All worked.

Now 'yarn start' and 'npm start' fail 

> mdbreact@4.2.0 start /home/jamesl/dev/React-Bootstrap-with-Material-Design
> yarn run sass-compile && concurrently --kill-others "yarn run sass-compile --watch" "yarn run webpack"

yarn run v1.5.1
$ node-sass dist/scss -o dist/css
{
  "status": 1,
  "file": "/home/jamesl/dev/React-Bootstrap-with-Material-Design/dist/scss/core/_mixins.scss",
  "line": 215,
  "column": 15,
  "message": "Functions may not be defined within control directives or other mixins.",
  "formatted": "Error: Functions may not be defined within control directives or other mixins.\n        on line 215 of dist/scss/core/_mixins.scss\n>>     @function set-notification-text-color($color) {\n\n   --------------^\n"
}
error An unexpected error occurred: "Command failed.
Exit code: 1
Command: sh
Arguments: -c node-sass dist/scss -o dist/css
Directory: /home/jamesl/dev/React-Bootstrap-with-Material-Design
Output:
".
info If you think this is a bug, please open a bug report with the information provided in "/home/jamesl/dev/React-Bootstrap-with-Material-Design/yarn-error.log".

**Comment by bezerrathm** [comment]
I had the same problem here.
The alternative I found was to change the version of the node-sass package in the package.json file to:

"node-sass": "^ 3.4.2"

**Comment by jamesladd** [comment]
Thank you.

**Comment by smolenski-mikolaj** [comment]
Thanks for letting us know about node-sass. We'll test MDB React with all latest versions of that package to find errors.

**Comment by jamesladd** [comment]
Sorry I didn’t have time to do this for you and post a pull request.
