### ISSUE TITLE
The mdbreact is installed with react version 15.6.1 but it can be imported

### ISSUE THREAD

**Issue by thecassion** [mdbootstrap/mdb-react-ui-kit#3]
`
Failed to compile.

./src/App.js
Module not found: Can't resolve 'mdbreact' in '/home/mypersonal/reactjs/src'
`

**Comment by jasiek-net** [comment]
Try this: `import { Card } from 'mdbreact/src'`

**Comment by SnakeHead** [comment]
Not working for me, using:  import { Nav } from 'mdbreact/src'
I get: Uncaught SyntaxError: Unexpected token import

Using: import { Nav } from 'mdbreact'
I get: Module not found: 'mdbreact' in /Users/geraldbailey/Desktop/react-router-firebase-auth-master/src/components

**Comment by carlgrimm** [comment]
The uncaught token import may be from not using transform-object-rest-spread in your babel plugins. Also you can see they alias their /src directory in [webpack.config.js](https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/blob/master/webpack.config.js) which fixed the resolve issues for me.

**Comment by mattonit** [comment]
Fixed :)
