### ISSUE TITLE
Does NavBar component support background-color changing when scrolling?

### ISSUE THREAD

**Issue by nguyenhuutinh** [mdbootstrap/mdb-react-ui-kit#30]
### Expected behavior
like this page: https://mdbootstrap.com/wp-content/themes/mdbootstrap4/content/jquery/tutorials/bootstrap/tutorial-2/10/index.html
### Your working environment and MDB version information
4.2.0
### Resources (screenshots, code snippets etc.)

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by JStrebeyko** [comment]
Not out of the box, but it is pretty easy to implement. In the `Navbar` component you can tell that once the `window.pageYOffset` overgrows `scrollingNavbarOffset`, it triggers a `isCollapsed` state change, what in turn influences contents in the `let classes` variable. Just enrich the ternary with your predefined class regarding a color change and voilà! Best, Kuba

**Comment by bkrajendra** [comment]
If you want to change navbar bg on scroll after a specific point on-page, then this might help:

```

$(document).ready(function(){   
   var scroll_start = 0;
   var startchange = $('#startchange');
   var offset = startchange.offset();
    if (startchange.length){
   $(document).scroll(function() { 
       
      scroll_start = $(this).scrollTop();
      //console.log("sc1 " + scroll_start);
      if(scroll_start > offset.top) {
          $(".navbar-dark").addClass('gradient-nav');
          
       } else {
          $('.navbar-dark').css('background-color', 'transparent!important');
          $(".navbar-dark").removeClass('gradient-nav');
       }
   });
    }
});

```

```#startchange``` is an element at which when scrolled, the color of nav bg will change.
the class can be any as per requirement.
