### ISSUE TITLE
Cannot use .jsx extension, webpack fails to compile

### ISSUE THREAD

**Issue by AderCode** [mdbootstrap/mdb-react-ui-kit#31]
### Expected behavior
To be able to use `.jsx` extension for use with emmet shortcuts.

### Actual behavior
when using a `.jsx` extension webpack fails to compile.
when extension is changed to `.js`, everything compiles correctly.

### Your working environment and MDB version information
MDB: 4.2.0
Node: 9.3.0
VSCode v1.22

### Resources (screenshots, code snippets etc.)

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by smolenski-mikolaj** [comment]
This problem is connected with the webpack config of MDB React. We'll try to fix it in the future. Thanks for letting us know about the error.
