### ISSUE TITLE
$image-path - issues

### ISSUE THREAD

**Issue by muehle28** [mdbootstrap/mdb-react-ui-kit#32]
Line 154 of _variables.scss: after the $image-path variable the "!default" is missing, so its not possible to override the value ($image-path: "../img/";)

Line 81 of _masks.scss: image-path is hardcoded
    background: url("../img/overlays/#{$filename}.png");

**Comment by smolenski-mikolaj** [comment]
This issues will be fixed with the next release.
In masks.scss it should be:

@each $no, $filename in $patterns {
 .pattern-#{$no} {
   background: url("#{$image-path}/overlays/#{$filename}.png");
 }
}

**Comment by muehle28** [comment]
Do you know already when the release date will be? Yarn is updating my changes everytime I add a new library.

**Comment by smolenski-mikolaj** [comment]
Most likely it will be 21.05

**Comment by Jaid** [comment]
I can confirm both of these issues. My temporary fix is creating a symlink at `$image-path` that references to the existing `img/` folder.

In terminal:
```bash
ln -s ../../node_modules/mdbootstrap/img/ src/components/img
```

`theme.scss`
```scss
$roboto-font-path: "~mdbootstrap/font/roboto/";

@import "~mdbreact/dist/scss/mdb.scss";

$image-path: "~mdbootstrap/img"; // Currently not working: https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/issues/32
```

**Comment by Rotarepmi** [comment]
I assume that this issue can be closed.
