### ISSUE TITLE
how to increase interval in carousel react component

### ISSUE THREAD

**Issue by kkbeheramca** [mdbootstrap/mdb-react-ui-kit#33]
### Expected behavior
to increase interval in react carousel

### Actual behavior
it is taking default interval 5000

### Your working environment and MDB version information
Material Design for Bootstrap 4 (React version)

**Comment by JStrebeyko** [comment]
Hi there,
`<Carousel>` takes in an `interval` props, specifying a number of milliseconds after which it will be performing the next() function. Therefore, Carousel’s interval in MDB React is set with, for example, `<Carousel interval={8000}>`.

**Comment by kkbeheramca** [comment]
thanks JStrebeyko , 
i tried this way of setting interval as you mentioned even tried direct data attribute such as data-interval="10000" , but none of these working , it takes default 5000 as interval. when debug through carousel.js or index.js in dist i saw the hardcoded value set to "5000" i guess there is no props overriding it from props set interval.
can you let me know if this works for you then which build or little more detail on this

**Comment by JStrebeyko** [comment]
Hey @kkbeheramca ,
You are right in that it takes in a default value, but it's <a href="https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/blob/d0faffbabd351a6644a41a9848fb72a4d1cf13e0/src/components/Carousel.js#L83">6000</a>, not 5000. Moreover, it is _default_ as in _defaultProps_, meaning it is **made** to be <a href="https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/blob/d0faffbabd351a6644a41a9848fb72a4d1cf13e0/src/components/Carousel.js#L46">overriden with props</a>, and never hard-coded.

The kind of problems you are getting (mainly, assuming a wrong default value, but also trying to use data-* attributes) suggests you are using a wrong repo or a good one the wrong way. Please refer to <a href="https://mdbootstrap.com/react/">the docs</a> for guidence.

Best, Kuba

**Comment by kkbeheramca** [comment]
thanks @JStrebeyko , i guess my version is different and it shows 5000 was default value set without prop defined. i will have to upgrade to this version or copy of components. 
thank you again.
