### ISSUE TITLE
Documentation looks vague

### ISSUE THREAD

**Issue by johadi** [mdbootstrap/mdb-react-ui-kit#36]
Your documentation on installing this package to work with React ( [link](https://mdbootstrap.com/react/5-min-quick-start) ) is not appropriate, lacks some info. In the doc, it is said to just install the package and start using it whereas , you need to import the following:
```
import 'bootstrap/dist/css/bootstrap.css'
import 'mdbreact/dist/css/mdb.css'
```
You guys should correct this. Also, the installation guide for setting this package with create-react-app is inappropriate; it never works for me. You guys probably want to take a look at the whole installation guide you provided for react as everything looks vague. I had to download the package, check the whole project to get brief understanding of how things work together before I actually made headway on using it. Good job done but please, let the user be pleased by giving them good doc.

**Comment by smolenski-mikolaj** [comment]
Thanks for Your remarks. We'll update docs with the next release.

**Comment by FernandoBoza** [comment]
@johadi thank you! I was looking for this everyone

**Comment by Mikuu** [comment]
@smolenski-mikolaj I'm also got lost about the React version documentation, I searched around your whole site, but haven't found any detailed documentation about the MDB react version usage, e.g. the component API. 

Is there any documentation or reference guide about the React version?

**Comment by smolenski-mikolaj** [comment]
Here's the link to our React docs: https://mdbootstrap.com/react/
