### ISSUE TITLE
Pills throw error when used

### ISSUE THREAD

**Issue by at0mzk1** [mdbootstrap/mdb-react-ui-kit#37]
### Expected behavior
Pills should be rendered within the container defined.
### Actual behavior
Console is showing an error: 
`Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

### Your working environment and MDB version information
Platform: Windows
Node: v9.0.0
React: v16.3.2
MDB: 4.4.0

### Resources (screenshots, code snippets etc.)

Error is happening specifically at TabContent and TabPane elements
```
<TabContent activeItem={this.state.activeItemPills}>
    <TabPane tabId="1">
            <LoginForm />
    </TabPane>
    <TabPane tabId="2">
        <SignUpForm />
    </TabPane>
</TabContent>
```

Also a bonus note: I suspect pills are a premium feature, and if this is so, then please tag appropriately in your documentation (https://mdbootstrap.com/react/advanced/tabs/#pills), too bad you guys didn't even implement a basic version of tabs for us free users.

**Comment by JStrebeyko** [comment]
Hi there, our bad - it was indeed rather confusing. Thanks for taking time and letting us know!

**Comment by at0mzk1** [comment]
Pills tagged appropiately, issue solved.

**Comment by blackflow** [comment]
> Pills tagged appropiately, issue solved.

How did you solve this issue? I am having a similar error, when I include <TabContent>

**Comment by at0mzk1** [comment]
> > Pills tagged appropiately, issue solved.
> 
> How did you solve this issue? I am having a similar error, when I include

I didn't solve it, pills are a premium feature so unless you pay the license then you won't be able to use them.
