### ISSUE TITLE
There is compatible problem with browser other than chrome

### ISSUE THREAD

**Issue by PhantomX7** [mdbootstrap/mdb-react-ui-kit#38]
when i wrap Link tag from react-router-dom to a CardImage it is working fine on chrome. But when I was on firefox or mobile browser, I need to double click the image in order to make the Link working.

working on react 16, react-router 4,  MDB React: 4.4.0

```javascript
<Link to={`/dashboard/product/${this.props.product_id}`}>
    <CardImage
        className="img-fluid"
        src={this.props.image}
     />
</Link>
```

**Comment by smolenski-mikolaj** [comment]
Thanks for Your remarks. We'll work on it and try to prepare a fix for it in the next release.

**Comment by Rotarepmi** [comment]
Issue was related to the Waves functionality. It was fixed and should not bother anyone anymore.
