### ISSUE TITLE
Unsafe Lifecycle in dropdown toggle modal

### ISSUE THREAD

**Issue by HenryTanjaya** [mdbootstrap/mdb-react-ui-kit#39]
When i click the dropdown toggle there's an issue with unsafe legacy lifecycles
working on react 16, react-router 4, MDB React: 4.4.0

```
Warning: Unsafe legacy lifecycles will not be called for components using new component APIs.

ButtonBase uses getDerivedStateFromProps() but also contains the following legacy lifecycles:
  componentWillReceiveProps

The above lifecycles should be removed. Learn more about this warning here
```

**Comment by JStrebeyko** [comment]
Hi there,
So, what is ButtonBase exactly? - I understand it is the `dropdown toggle modal` you mention, but I am afraid it is not part of MDB React. Could you link to it? Best, Kuba

**Comment by HenryTanjaya** [comment]
it shows up on console when I use Dropdown, DropdownToggle, DropdownMenu component. For exact when I clicked the button to open the dropdown toggle.
Thanks for replying anyway.

**Comment by Rotarepmi** [comment]
All unsafe methods have been replaced.
