### ISSUE TITLE
Deploying to Heroku

### ISSUE THREAD

**Issue by samuelzxu** [mdbootstrap/mdb-react-ui-kit#40]
How do I configure this for deployment to heroku? I tried a bunch of the methods listed elsewhere online (adding the static.json, etc) but I'm still getting a 404 error. Help is greatly appreciated!

**Comment by mattonit** [comment]
what have you tried so far?

**Comment by samuelzxu** [comment]
Adding a static.json file with
`{
    "root": "build/",
    "clean_urls": false,
    "routes": {
      "/**": "index.html"
    }
}`

Restarting the dyno on heroku, adding a proxy field in package.json.

**Comment by Rotarepmi** [comment]
I'm closing the issue, which is not an issue in all.

https://devcenter.heroku.com/articles/deploying-nodejs
Build should be deployed

Regards
