### ISSUE TITLE
Webpack 4 support ?

### ISSUE THREAD

**Issue by aramis-it** [mdbootstrap/mdb-react-ui-kit#41]
### Resources (screenshots, code snippets etc.)

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by JStrebeyko** [comment]
Hi there, 
We have not yet checked compatibility and migration route completely, so we can take no responsibility for what it does to the project. Thanks for reaching out, though - the performance improvements makes it worthwhile, so we are definitely going to have a look at it.
Best, Kuba

**Comment by Rotarepmi** [comment]
Compatible with Webpack 4 since v.4.7.0
