### ISSUE TITLE
react-scripts is listed as a dependency instead of a devDependency

### ISSUE THREAD

**Issue by jim-moody** [mdbootstrap/mdb-react-ui-kit#44]
### Expected behavior
`react-scripts` should be a devDependency

### Actual behavior
`react-scripts` is a dependency. This _dramatically_ increases node_modules size when including `mdbreact` in a node project.

### Resources (screenshots, code snippets etc.)
Size with `react-scripts`:
<img width="402" alt="screen shot 2018-08-06 at 10 22 45 am" src="https://user-images.githubusercontent.com/26190589/43722485-5bd890d6-9963-11e8-819f-9857e53cff9a.png">

Size without `react-scripts`:
<img width="375" alt="screen shot 2018-08-06 at 10 24 16 am" src="https://user-images.githubusercontent.com/26190589/43722521-713feece-9963-11e8-8381-a68357b3c389.png">

For every **question of technical nature**, in order to get the most detailed answer as soon as possible, ask on our dedicated [Support Forum](https://mdbootstrap.com/support/)

**Comment by mattonit** [comment]
Thank you for this PR! We'll review this PR and I hope to see your PR merged ;)

**Comment by jim-moody** [comment]
This is fixed in 4.7.0
