### ISSUE TITLE
Is this a product to buy?

### ISSUE THREAD

**Issue by zz80** [mdbootstrap/mdb-react-ui-kit#46]
### Expected behavior
based on react 16, less warnings
### Actual behavior

npm install mdbreact

npm WARN deprecated react-popper@0.7.5: please use 0.7.4 or 8.0.0 and above

> jss@9.8.7 postinstall /home/salvo/Documenti/progettiLocal/test-react/node_modules/jss
> node -e "console.log('\u001b[35m\u001b[1mLove JSS? You can now support us on open collective:\u001b[22m\u001b[39m\n > \u001b[34mhttps://opencollective.com/jss/donate\u001b[0m')"

Love JSS? You can now support us on open collective:
 > https://opencollective.com/jss/donate

> material-ui-pickers@1.0.0-rc.13 postinstall /home/salvo/Documenti/progettiLocal/test-react/node_modules/material-ui-pickers
> node -e "console.log('\u001b[35m\u001b[1mHave you installed one of peer libraries?\u001b[22m\u001b[39m\n > date-fns \n > luxon \n > moment')"

Have you installed one of peer libraries?
 > date-fns 
 > luxon 
 > moment
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN react-motion-ui-pack@0.10.3 requires a peer of react@0.14.x || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN react-motion-ui-pack@0.10.3 requires a peer of react-dom@0.14.x || ^15.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ mdbreact@4.7.0
added 96 packages from 137 contributors and audited 13052 packages in 17.258s
found 0 vulnerabilities
### Your working environment and MDB version information
Ubuntu 18.04, node 10.8.0

have I to install two versions of react or remain on react 15?

### npm WARN bootstrap@4.1.3 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
Is really jquery free?

**Comment by Rotarepmi** [comment]
Thank you for posting. Still working on improvements and removing additional dependencies. Thus this is not an issue, I'm closing the topic. Will inform in changelogs.
And yes, it was and is Jquery free, bootstrap was just shouting that it needs JQ.

Regards
