### ISSUE TITLE
Popover, custom element - Feature suggest

### ISSUE THREAD

**Issue by JustinMartinDev** [mdbootstrap/mdb-react-ui-kit#49]
Hello, 

The element <Popover> does not allow to set a custom element. It must be a basic HTML element and you can just specify the body text. It would be a good idea to update <Popover> to allow the usage of custom element. 

Justin,

**Comment by Rotarepmi** [comment]
Hey,

Popover was meant to expose just some text description as it is in Bootstrap.
We will submit your proposal to the discuss.

Due to the fact it is not an issue, I'm closing the topic.

Best regards
