### ISSUE TITLE
Button, custom color - Feature suggest

### ISSUE THREAD

**Issue by JustinMartinDev** [mdbootstrap/mdb-react-ui-kit#50]
Hey,

It's impossible to use specific color who are not "primary, secondary, pink, .." in the "color" attribut like that

`<Button color="#c0392b">Add</Button>`

To do it I had to did it :  
`<Button className="red-color" color="">Add</Button>`
`.red-color { 
    background-color: #c0392b
}`

I think it should be nice to allow this : 
`<Button color="#c0392b">Add</Button>`

If the color is not a predefined color just add a style balise like this : 
`style={"background-color:"+this.color+"} `

**Comment by Rotarepmi** [comment]
Good sugestion @JustinMartinDev, thanks for pointing out.
We will put into use in the future release.

Regards

**Comment by Rotarepmi** [comment]
After consideration it becomes that it is not compatible with Bootstrap's approach within this area. Colors should be predefined, to provide usability with classes like btn-outline (as it is in bootstrap).

**Comment by Rotarepmi** [comment]
Thanks again for suggestion. I'm closing the issue for now
