### ISSUE TITLE
Input - Docs update

### ISSUE THREAD

**Issue by JustinMartinDev** [mdbootstrap/mdb-react-ui-kit#51]
Hello (once again), 

I think you should add in the documentation that the `<Input>` can had the attribut "name"

`<Input name="myfieldname" icon="user" group label="Label field"/>`
and the html corresponding : 
```
<div class="md-form form-group">
    <i class="fa fa-user prefix"></i>
    <input name="myfieldname" class="form-control" value=""/>
    <label class="">Label field</label>
</div>
```

**Comment by Rotarepmi** [comment]
'name' is semantic part of HTML, which is required to describe form's content. 
So we did not mentioned it intentionally.

Anyway, thanks for suggestion, we will discuss it. 
I'm closing the issue.

Best regards
