### ISSUE TITLE
React MDBoostrap break SSR : window is not defined

### ISSUE THREAD

**Issue by ylacaute** [mdbootstrap/mdb-react-ui-kit#52]
### Expected behavior
We should be able to build and run a server side rendered application.

### Actual behavior
When running SSR application, we got this error :
```
ReferenceError: window is not defined
    at Object.../node_modules/mdbreact/dist/mdbreact.js
```

### Your working environment and MDB version information
Webpack: 4.24.0
react: 16.6.0
mdbreact: 4.8.2
Typescript: 3.1.6
Debian 4.9.110-3+deb9u6 (2018-10-08) x86_64 GNU/Linux

### Resources (screenshots, code snippets etc.)
```
!function(e,t){ true?module.exports=t(__webpack_require__(/*! prop-types */ "../node_modules/prop-types/index.js"),__webpack_require__(/*! react */ "../node_modules/react/index.js"),__webpack_require__(/*! classnames */ "../node_modules/classnames/index.js"),__webpack_require__(/*! react-popper */ "../node_modules/react-popper/lib/react-popper.js"),__webpack_require__(/*! react-dom */ "../node_modules/react-dom/index.js"),__webpack_require__(/*! react-transition-group */ "../node_modules/react-transition-group/index.js"),__webpack_require__(/*! react-toastify */ "../node_modules/react-toastify/lib/index.js"),__webpack_require__(/*! react-router-dom */ "../node_modules/react-router-dom/es/index.js"),__webpack_require__(/*! react-numeric-input */ "../node_modules/react-numeric-input/index.js"),__webpack_require__(/*! outy */ "../node_modules/outy/index.js")):undefined}(window,function(e,t,n,r,o,a,i,c,l,u){return function(e){var t={};functio

ReferenceError: window is not defined
    at Object.../node_modules/mdbreact/dist/mdbreact.js (/home/epi/Prog/boilerplates/react-ssr/dist/server/app.bundle.js:26136:881)
    at __webpack_require__ (/home/epi/Prog/boilerplates/react-ssr/dist/server/app.bundle.js:20:30)
    at Module../components/sample/SampleButtons.tsx (/home/epi/Prog/boilerplates/react-ssr/dist/server/app.bundle.js:78991:66)
```

I was able to get the application running with webpack-dev-server OR with SSR.
After I added mdboostrap, I was only able to get the application running with webpack-dev-server, the SSR is broken because that window.

I probably found the problem : you are packaging the application with "style-loader" which is not compatible with SSR. I have done some tests by rebuilding bootstrap-material-design differently :

1.  using the **mini-css-extract-plugin**, as a consequence we need to import a new generated css file
2.  using **isomorphic-style-loader** instead of style-loader 

Both solution works. As the first one have the drawback to add another CSS import (5k extracted from the JS) I finaly choose the second one. 

PR : https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/pull/53
Please check I didn't beack anything, it works on my project but I am just discovering your library and only verified Buttons :D

I will close the previous issue that I created in the wrong repository (https://github.com/mdbootstrap/bootstrap-material-design/issues/196)

**Comment by ylacaute** [comment]
Don't accept this PR, styles are broken : I still need to import the previously generated CSS with mini-css-extract-plugin in order to get something working. (I forgot to remove it to test correctly).

Finally the only solution working is to use mini-css-extract-plugin. The will impact developpers wich will have to import another CSS, are you ok with that ?

**Comment by Rotarepmi** [comment]
Hey there,
Thanks for a tone of the good job. SSR is truerly the weak point of our package. 

Unless its not only problem with css I can't tell how much this solution will help here. 
There are some more complex components, which appeal to the window object. This might crash the SSR too. We are slightly working on it, but its a time and resource consuming process.

After we discuss and, obviously, test your solution, I will back with the feedback.

Thanks again, keep hacking! :)

**Comment by Rotarepmi** [comment]
Hi @ylacaute 

We have been working on the problem for some time, and it is clearly not the case with our CSS. It is mostly connected with the setup of your ssr engine and how our bundle looks like. We are currently implementing Rollup and it is going to be awesome. It provides better support for features like tree-shakedown and ssr. Also we are working currently on integration with Gatsby and Next.js, so stay tooned -> we will tell more in near future.

Wish you best,

Jakub
