### ISSUE TITLE
Bootstrap hover effects not works in react component

### ISSUE THREAD

**Issue by mrajeshkrossark** [mdbootstrap/mdb-react-ui-kit#54]
Hi,

I tried to implement hovering effects but am not getting it. I dont know what piece am missing. is the problem with my end?

```
import { View, Mask } from 'mdbreact';

    render() {
        return (
                       <div>
                        <div className="row">
                            <div className="col">
                                <h2>My Templates</h2>
                            </div>
                            <div className="col">
                                <Button className="action_button float-right" type="primary">Create Templates</Button>
                            </div>
                        </div>
                            <View overlay="red-strong">
                                <img src="https://mdbootstrap.com/img/Photos/Others/forest-sm.jpg" className="img-fluid" alt="" />
                                <Mask className="flex-center">
                                    <p className="white-text">Strong overlay</p>
                                </Mask>
                            </View>
</div>
);}
```

My output is:

![image](https://user-images.githubusercontent.com/22819712/48780954-0639c680-ed01-11e8-87ca-8fe847ee595a.png)

**Comment by Rotarepmi** [comment]
Hi,
There are some lacks in documentation, but we are currently working on new standard.
You have to add property `hover` to View component.
`<View hover>`
And property `overlay` has been moved to `Mask` component.
`<Mask overlay="red-strong"`

**Comment by mrajeshkrossark** [comment]
> Hi,
> There are some lacks in documentation, but we are currently working on new standard.
> You have to add property `hover` to View component.
> `<View hover>`

thanks it works...

**Comment by alirizvi061** [comment]
This is not working, I have a client website to finish. Please assist:  
             <div>
                <View hover>
                    <img className="projectImage" src="Home-page-projects-pic.png" alt="" />
                    <Mask className="flex-center" overlay="red-strong"
                    >
                        <p className="white-text">Strong overlay</p>
                    </Mask>
                </View>
            </div>

**Comment by alirizvi061** [comment]
This is not functioning on my react app, please assist. Here is the code: 

`         <div>
                <View hover>
                    <img className="projectImage" src="Home-page-projects-pic.png" alt="" />
                    <Mask className="flex-center" overlay="red-strong"
                    >
                        <p className="white-text">Strong overlay</p>
                    </Mask>
                </View>
            </div>`
