### ISSUE TITLE
npm ERR! Failed at the mdbreact@4.8.4 start script.

### ISSUE THREAD

**Issue by RasikaKshirsagar** [mdbootstrap/mdb-react-ui-kit#55]
Getting below error while running the project. Can somebody please check this issue asap.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mdbreact@4.8.4 start: `yarn run webpack`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mdbreact@4.8.4 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Rasika kshirsagar\AppData\Roaming\npm-cache\_logs\2018-11-27T12_38_40_871Z-debug.log

**Comment by Rotarepmi** [comment]
If you cloned the repo, you have to install dependencies first - _npm install_
