### ISSUE TITLE
ToastContainer component not working

### ISSUE THREAD

**Issue by Jacob8765** [mdbootstrap/mdb-react-ui-kit#56]
The ToastContainer component throws this error whenever I try to use it:

`Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

I am importing it like this `import { ToastContainer, toast } from "mdbreact";`, and using it in my app like this:

` <ToastContainer
       hideProgressBar={true}
       newestOnTop={true}
       autoClose={5000}
  />`

**Comment by Rotarepmi** [comment]
Toast/Notification is a pro component.
[https://mdbootstrap.com/docs/react/advanced/notifications/](https://mdbootstrap.com/docs/react/advanced/notifications/)

Please update to [pro version](https://mdbootstrap.com/products/react-ui-kit/) in case you want to use it - and many more components.

Regards
