### ISSUE TITLE
How to set focus on input?

### ISSUE THREAD

**Issue by shaggyrec** [mdbootstrap/mdb-react-ui-kit#57]
Or how get access to the html input element

**Comment by Rotarepmi** [comment]
That is kind of trick. You have to use Ref and then findDOMNode for that Ref.
Seems like a thing which we could improve.

Thanks for posting the question.

**Comment by Rotarepmi** [comment]
Hey,

Please check our newest update. Inputs have been rewritten and they should perform much better.
You can use them as the controlled or uncontrolled input, and set your callback refs.

Best,
Jakub
