### ISSUE TITLE
Error establishing a database connection

### ISSUE THREAD

**Issue by RamyaAshika** [mdbootstrap/mdb-react-ui-kit#63]
This is what I'm getting when I go for documentation or demo in online.

**Comment by mattonit** [comment]
Our website is up again

**Comment by danndav** [comment]
getting the same error now

**Comment by mattonit** [comment]
All of our services are up and running again

**Comment by agent-uno** [comment]
I still encountered "Error establishing a database connection". What can we do to access your documentation?

**Comment by almonty67** [comment]
I have been getting the same Error also all day yesterday and I just checked and I am still getting same Error

**Comment by ondrejjcizek** [comment]
Still the same problem right now

**Comment by mattonit** [comment]
We're doing our best to resolve this issue as quickly as we can

**Comment by WhiteBookmark** [comment]
I'm getting this error too, unable to access the site now.
