### ISSUE TITLE
MDB Datatable select all with checkbox

### ISSUE THREAD

**Issue by RamyaAshika** [mdbootstrap/mdb-react-ui-kit#64]
Hi
    I'm trying to do https://mdbootstrap.com/docs/react/tables/additional/ like this but with select all option. 
  But I can't able to achieve this using mdb bootstrap. May I get any help on this or any documentation?

**Comment by KrishnaPayyavula** [comment]
Hie ,

I do have the same problem. They have not given any proper documentation on this and click events.

**Comment by RamyaAshika** [comment]
Hey Hi @KrishnaPayyavula 
   Now only I have fixed that problem. Try to use it using dataFormatter.

**Comment by KrishnaPayyavula** [comment]
Hie @RamyaAshika 

What do you mean by dataFormattter?

Could you please share an example code for select all and click handler in data tables

**Comment by RamyaAshika** [comment]
https://stackoverflow.com/questions/37705307/get-the-row-data-by-a-button-in-a-react-bootstrap-table

**Comment by RamyaAshika** [comment]
Go through this link but instead of this MDBReact go with bootstrap table  http://allenfang.github.io/react-bootstrap-table/index.html for select all & You can achieve both. @KrishnaPayyavula

**Comment by Rotarepmi** [comment]
Hi,

I'm sure we can achieve what you need using just mdbreact's DataTables or Tables, but first, we need to know what exactly is the goal? Do you need table with checkboxes or table which allows you to select the row by clicking it?

You can attach events to the rows by `clickEvent` prop inside your data object. Check our DataTables documentation: https://mdbootstrap.com/docs/react/tables/datatables/

Or you can use an example from here: https://mdbootstrap.com/docs/react/tables/additional/#table-with-panel

Checkboxes are controlled inputs, so you can use `onChange` method (or our `getValue`) and update your state with checked values. https://mdbootstrap.com/docs/react/forms/checkbox/

Best regards,

Jakub

**Comment by Rotarepmi** [comment]
I'm closing the issue due to long inactivity.
