### ISSUE TITLE
MDBNavbar with ScrollableAnchor

### ISSUE THREAD

**Issue by MarcelWepper** [mdbootstrap/mdb-react-ui-kit#66]
Hello,
I've got a problem with my navbar navigation.
I have got a working navbar, and I am trying to implement a single page application with anchors.
For that I am using Scrollable Anchor.
I placed the anchors on my landing page and referring them in my navbar:
            `<MDBNavItem>`
              `<MDBNavLink to="/#hero">Home</MDBNavLink>`
            `</MDBNavItem>`
But when I click the item on the navbar, nothing happens. 
The URL changes, but it is not moving to my anchor.
(example.com/#hero)

Ironically, when I am not on my landing page (example.com/contact) and I am using the anchor, it works!

Can someone help me?

Best regards

**Comment by Rotarepmi** [comment]
MDBNavLink is, in fact, the react router's Link component.
You could implement your own link element with smooth scrolling, or try our pro component: https://mdbootstrap.com/docs/react/advanced/scroll/

Best,

Jakub

**Comment by MarcelWepper** [comment]
Hello Jakub,

thanks for your help.
I implemented my own link element with smooth scrolling.

Best regards
