### ISSUE TITLE
cannot import MDBTableEditable

### ISSUE THREAD

**Issue by fcpauldiaz** [mdbootstrap/mdb-react-ui-kit#69]
This gives me the following error
```js
import {
  MDBCard,
  MDBCardHeader,
  MDBCardBody,
  MDBTableEditable
} from 'mdbreact';
```
 
'MDBTableEditable' is not exported from 'mdbreact'.

How can I fix this?

**Comment by phares** [comment]
Was a fix to this issue found? i have the same problem.

**Comment by fcpauldiaz** [comment]
It was a Pro Component

**Comment by zubairshakoorarbisoft** [comment]
Hi, I have same issue. Can you please suggest the solution?
Thank you.
