### ISSUE TITLE
autocomplete with xhr request

### ISSUE THREAD

**Issue by rootsher** [mdbootstrap/mdb-react-ui-kit#72]
I'd like to do an autocomplete based on a request. When a character is written, the request is made, and the list is filled in based on the response.

By the way...autocomplete is practically always based on a large list, where does the idea of running on a predefined client-side come from?

**Comment by Rotarepmi** [comment]
Hi,

The list is predefined on the client side just for presentation purposes.  
You can use `getValue` method to control the input and do your fetch on change, then attach your data via `data` property.

For further discussions/help please ask `Ask Question` on our support forum https://mdbootstrap.com/support/ (you will get your answers faster there).

Best,
Jakub

**Comment by rootsher** [comment]
So..I should write my own component for this.. okay. When I'm done, I will publish the package ;)

**Comment by Rotarepmi** [comment]
Good attitude! :)

If you would be so nice, share it with our community. We will appreciate it :)

I'm closing the issue.

Best,
Jakub
