### ISSUE TITLE
@types/mdbreact for mdbreact project

### ISSUE THREAD

**Issue by rootsher** [mdbootstrap/mdb-react-ui-kit#73]
I am not satisfied with the lack of defined types for the mdbreact project. I would like to integrate this module into a project where I use TypeScript.
When are you able to do it?
It's hard to operate without hinting at the types, still looking into the source files. I also lack full, extensive documentation to know the full capabilities of the component.

Could someone specify when you plan to implement the above?

**Comment by Rotarepmi** [comment]
You can find detailed documentation here: https://mdbootstrap.com/docs/react/
We're sorry, but the TypeScript is not yet supported by the package and there are no near future plans of developing TS. 

Best,
Jakub
