### ISSUE TITLE
Build and deploy problems

### ISSUE THREAD

**Issue by Shmata** [mdbootstrap/mdb-react-ui-kit#79]
Hi guys , I need help to build and deploy my project.  I created some components inside "React-Bootstrap-with-Material-Design" package  after I've done, I run 
`npm run build`
then **dist** folder generated successfully but inside dist folder there isn't **index.html** and I don't know how to move my project to another server . 
![new](https://user-images.githubusercontent.com/2398297/59998643-33729c80-9675-11e9-8d75-b8127610c1cf.png)

in most of react projects after final build there are some files like below, 
that help developers to move their projects.
![old](https://user-images.githubusercontent.com/2398297/59998710-6321a480-9675-11e9-8c48-4e9d7bf37219.png)

My question is :  How to move and deploy my built project on another folder or another server ?

**Comment by Rotarepmi** [comment]
@Shmata use that ./static folder. Bundle from ./dist should be linked to your ./static/index.html

If you would like to try serving on github-pages I recommend using https://www.npmjs.com/package/gh-pages :)

**Comment by Rotarepmi** [comment]
@Shmata you have generated another version of the library. 
If you want to make an application you should use [Boilerplate](https://mdbootstrap.com/download/mdb-react/free/4.17.0_1a56fe18cdf31b98dbb7c41b2184ddc4/MDB-React-Free-npm.zip)

Or you can now use `npm pack` and attach your modified library to new React project :)
