### ISSUE TITLE
Could you make DataTableComponents public to allow better DataTable customization?

### ISSUE THREAD

**Issue by bakanov** [mdbootstrap/mdb-react-ui-kit#82]
I would like to customize some behavior in MDBDataTable. It would be nice to use components from  DataTableComponents folder, but they are not exported.

**Comment by AAndrasiuk** [comment]
Hi,

In what way you want to customize these components? Maybe this will be possible without exporting them. 

As one of the options, you can download our Datatable components and add them as separate files to your project.  And then you can customize them as you want. 

Best regards.
