### ISSUE TITLE
Buttons do not allow screen scrolling by dragging on mobile devices when used starts dragging within the button

### ISSUE THREAD

**Issue by psantiagomm** [mdbootstrap/mdb-react-ui-kit#85]
Hello, 
buttons do not allow screen scrolling by dragging on mobile devices when user starts dragging within the button.

Here you can observe the unwanted behavior:
https://react.mdbootstrap.com/components/buttons

Here you can observe the desired behavior:
https://mdbootstrap.com/docs/jquery/components/buttons/

Thank you

**Comment by kstepien3** [comment]
Hi @psantiagomm ,

Thank you for the founded bug!

We will fix this in the near future.

Best regards.
