### ISSUE TITLE
Datatables with row fields as components are not sortable

### ISSUE THREAD

**Issue by hasnaeFadili** [mdbootstrap/mdb-react-ui-kit#89]
In case of row fields defined as components, the sort is not working for component column, despite the use of **sortRows** and **searchValue**.
After debugging I think the problem is related to the function `_defineProperty(_assertThisInitialized(_this), "checkField", function (field, a, b, direction)`, the return value should be 1 or -1 not a boolean. Hereafter my proposition:

```
_defineProperty(_assertThisInitialized(_this), "checkField", function (field, a, b, direction) {
var _ref = [_this.checkFieldValue(a, field), _this.checkFieldValue(b, field)],
aField = _ref[0],
bField = _ref[1];
return direction === 'desc' ? aField < bField ? 1 : -1 : aField > bField ? 1 : -1;
});
```

Thanks for your efforts.

**Comment by kstepien3** [comment]
Hi, @h-fadili

Thank you for your answer, but we have to test this code and edit for component because probably you did send to us a code after rendered from dev tools. We encourage to you to make pull request :) 

Best regards.

**Comment by hasnaeFadili** [comment]
Hello,

After checking github repository, there is already a pull request *"*Fix
sorting of table row field components *#80" by nordp. *That correct this
issue.

Best regards.

**Comment by pglejzer** [comment]
Thanks! We will implement it as soon as possible. Have a nice day.
