### ISSUE TITLE
ERROR: Module not found: Error: Can't resolve 'glamor' in

### ISSUE THREAD

**Issue by FernandoBoza** [mdbootstrap/mdb-react-ui-kit#9]
hey folks, so i downloaded the project from the site and ran 
`npm install` & `npm start` and the server starts up but stops at the err message above

Mac OS Sierra
Node v8.9.1
NPM V5.5.1

 Any help would be great, can't wait till the PRO version gets released

**Comment by exanders** [comment]
Hi,

I ran into the same issue, run this command in your app directory:

`npm install glamor`

And then start it again with `npm start`

Exa

**Comment by mattonit** [comment]
Glamor was added as a dependency to MDB React 4.1.0
