### ISSUE TITLE
How to make Editable Cells in DataTable

### ISSUE THREAD

**Issue by skyrbs** [mdbootstrap/mdb-react-ui-kit#92]
Hello Team,

Thanks for reading this. I am looking to implement on click of edit open new page or url or  Link.
Can you please lookout below and let me know what i am missing 

const data = {
    columns: [
      {
        label: 'Name',
        field: 'name',
        sort: 'asc'        
      },
      {
          label: 'Edit',
          filterable: false,
          Header: 'Click here',
          accessor: 'link',
          render: e => < Link to="hello"> Edit </ Link >,
      }
    ], 
    rows: userdata
  };
//  showing bellow 
< MDBDataTable  striped  bordered  small   data={data}  />

==============

**Comment by jakubchmura** [comment]
Hi.
I think you can find an answer in our documentation. Check this: [Click here](https://mdbootstrap.com/docs/react/tables/editable/)
Best, Kuba

**Comment by skyrbs** [comment]
Hey @JakubChm 
Thanks for you comment. Yes i checked it but i am not getting how do i use 

< Link to="hello"> Edit </ Link >  at every rows.....

**Comment by jakubchmura** [comment]
Hi, 
This problem that you write about does not apply to issue in the MDB product. So then I need to redirect your question to our MDB support forum. 

Best, Kuba
