### ISSUE TITLE
Bootstrap 4.4.x

### ISSUE THREAD

**Issue by auvipy** [mdbootstrap/mdb-react-ui-kit#94]

**Comment by pglejzer** [comment]
Hi,

what problem do you have? I guess that you wanted to communicate us there is a new bootstrap version. Yes, we know about that and we will probably update this in the next release. Do you have more issues to show? Have a nice day.

Best regards,
Piotr

**Comment by auvipy** [comment]
yes you are right.

**Comment by pglejzer** [comment]
we are using a package from https://github.com/fyockm/bootstrap-css-only/issues/47 
If they will update this about the new version of Bootstrap we will do the same. I asked about that in their issue section. I am closing this issue now. Thanks for the report.

**Comment by auvipy** [comment]
why would you need that? https://github.com/fyockm/bootstrap-css-only/issues/47

**Comment by pglejzer** [comment]
I think the person who did this in our package wanted to make easier to import all bootstrap CSS to this package. This dependency is old and for now, we will not change it. Sorry about that.

**Comment by auvipy** [comment]
lol
