### ISSUE TITLE
Attempted import error: 'MDBAvatar' is not exported from 'mdbreact'.

### ISSUE THREAD

**Issue by yogendrajs** [mdbootstrap/mdb-react-ui-kit#96]
First, I installed **mdbreact** package from [npm](https://www.npmjs.com/package/mdbreact). After adding the Component it is showing the following error. My React version is 16.12.0. 
`Attempted import error: 'MDBAvatar' is not exported from 'mdbreact'.`

Can anyone help me to resolve this issue?

**Comment by PedroNunezCode** [comment]
Same thing here. Have you found an answer yet?

**Comment by yogendrajs** [comment]
> Same thing here. Have you found an answer yet?

Not yet.
Hey contributors, can you pls help to resolve it?

**Comment by pglejzer** [comment]
What kind of component do you use where you have that error?

**Comment by yogendrajs** [comment]
> What kind of component do you use where you have that error?

Ya, I just wrote `import { MDBAvatar } from "mdbreact;` in one of my Component in React.js after installing it from [this npm](https://www.npmjs.com/package/mdbreact) package. But, it is showing this [error](https://github.com/mdbootstrap/React-Bootstrap-with-Material-Design/issues/96#issue-548060841).

**Comment by pglejzer** [comment]
`MDBAvatar` is available in the pro version of mdbreact.  This error occurs because you're trying to import this in the free version.

**Comment by yogendrajs** [comment]
Oh, got it. Thanks!

**Comment by OussamaGhamian** [comment]
Actually I have faced the same problem, so simply I put img tag instead of MDBAvatar and it worked.

**Comment by soltrenc** [comment]
What if I have the pro version and still have the error tag? How do I get rid of this error?

**Comment by aifeelit** [comment]
I have the pro versoin, But still have that error? what should I do next?
